#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders/vulkan"
OUT_HEADER="$SCRIPT_DIR/src/shaders/vulkan_widgets.h"

mkdir -p "$SCRIPT_DIR/src/shaders"

# ---------------------------------------------------------------------------
# Compile GLSL → SPIR-V
# ---------------------------------------------------------------------------
SHADERS=(rect.vert rect.frag quad.vert quad.frag)
SPV_FILES=()

for s in "${SHADERS[@]}"; do
    base="${s%.*}"
    stage="${s##*.}"
    spv="$SHADER_DIR/$base.$stage.spv"
    SPV_FILES+=("$spv")

    echo "Compiling: $s → $base.$stage.spv"
    glslangValidator -V "$SHADER_DIR/$s" -o "$spv"
done

# ---------------------------------------------------------------------------
# Generate header from SPIR-V binaries
# ---------------------------------------------------------------------------
python3 - "$OUT_HEADER" "${SPV_FILES[@]}" <<'PYEOF'
import sys
import os

def binary_to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

out_path = sys.argv[1]
spv_paths = sys.argv[2:]

arrays = []
for spv in spv_paths:
    name = os.path.basename(spv).replace(".", "_")
    hex_lines, size = binary_to_hex_lines(spv)
    arrays.append(f"""static const unsigned char k{name}[] = {{
{hex_lines}
}};

static const unsigned int k{name}Size = {size};
""")

header = f"""#pragma once

// Auto-generated by build_vulkan_shaders.sh — do not edit.
// Rebuild with: ./build_vulkan_shaders.sh

namespace systems::leal::campello_widgets::shaders {{

{chr(10).join(arrays)}
}} // namespace systems::leal::campello_widgets::shaders
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}")
PYEOF
