# Generates src/shaders/dx12_widgets.h from the compiled .cso (DXBC) files
# in shaders/dx12/. Invoked by build_dx12_shaders.bat — do not run directly
# unless the .cso files already exist.
param(
    [Parameter(Mandatory=$true)][string]$ShaderDir,
    [Parameter(Mandatory=$true)][string]$OutHeader
)

$csoFiles = @(
    "rect_vs.cso", "rect_ps.cso",
    "quad_vs.cso", "quad_ps.cso",
    "shape_vs.cso", "shape_ps.cso",
    "line_vs.cso", "line_ps.cso",
    "blur_vs.cso", "blur_ps.cso",
    "clip_shape_vs.cso", "clip_shape_ps.cso",
    "shader_mask_vs.cso", "shader_mask_ps.cso"
)

$arrays = New-Object System.Text.StringBuilder

foreach ($file in $csoFiles) {
    $path = Join-Path $ShaderDir $file
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $name = "k" + $file.Replace(".", "_")

    [void]$arrays.AppendLine("static const unsigned char ${name}[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 12) {
        $chunk = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
        $hex = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
        [void]$arrays.AppendLine("    $hex,")
    }
    [void]$arrays.AppendLine("};")
    [void]$arrays.AppendLine("")
    [void]$arrays.AppendLine("static const unsigned int ${name}Size = $($bytes.Length);")
    [void]$arrays.AppendLine("")
}

$header = @"
#pragma once

// Auto-generated by build_dx12_shaders.bat - do not edit.
// Rebuild with: build_dx12_shaders.bat

namespace systems::leal::campello_widgets::shaders {

$($arrays.ToString())} // namespace systems::leal::campello_widgets::shaders
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutHeader, $header, $utf8NoBom)
