#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders/metal"
OUT_HEADER="$SCRIPT_DIR/src/shaders/metal_widgets.h"
IOS_DEPLOYMENT_TARGET="16.0"

mkdir -p "$SCRIPT_DIR/src/shaders"

# ---------------------------------------------------------------------------
# Compile Metal → AIR → metallib
#
# Metal shader bytecode is platform-specific (it embeds a target triple), so
# a metallib built with `-sdk macosx` fails to load on iOS device/simulator
# with "library was not compiled for the simulator"/"...for iOS". This
# backend is shared by macOS and iOS (src/gpu/metal/), so all three variants
# are built and embedded; metal_draw_backend.mm picks the right one at
# compile time via TargetConditionals.h.
# ---------------------------------------------------------------------------
build_variant() {
    local sdk="$1" extra_flags="$2" suffix="$3"
    echo "Compiling ($sdk): widgets.metal → widgets_${suffix}.air"
    xcrun -sdk "$sdk" metal $extra_flags -c "$SHADER_DIR/widgets.metal" -o "$SHADER_DIR/widgets_${suffix}.air"
    echo "Linking   ($sdk): widgets_${suffix}.air → widgets_${suffix}.metallib"
    xcrun -sdk "$sdk" metallib "$SHADER_DIR/widgets_${suffix}.air" -o "$SHADER_DIR/widgets_${suffix}.metallib"
}

build_variant macosx           ""                                                     macos
build_variant iphoneos         "-mios-version-min=${IOS_DEPLOYMENT_TARGET}"            ios
build_variant iphonesimulator  "-mios-simulator-version-min=${IOS_DEPLOYMENT_TARGET}"  ios_simulator

# ---------------------------------------------------------------------------
# Generate header from the three metallib binaries
# ---------------------------------------------------------------------------
python3 - "$SHADER_DIR" "$OUT_HEADER" <<'PYEOF'
import sys

def binary_to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

shader_dir, out_path = sys.argv[1], sys.argv[2]

variants = [
    ("macOS",        f"{shader_dir}/widgets_macos.metallib"),
    ("iOS",           f"{shader_dir}/widgets_ios.metallib"),
    ("iOSSimulator",  f"{shader_dir}/widgets_ios_simulator.metallib"),
]

arrays = []
for name, path in variants:
    hex_lines, size = binary_to_hex_lines(path)
    arrays.append(f"""static const unsigned char kWidgetsMetalShader_{name}[] = {{
{hex_lines}
}};

static const unsigned int kWidgetsMetalShaderSize_{name} = {size};
""")
    print(f"Embedded: {path}  ({size} bytes)")

header = f"""#pragma once

// Auto-generated by build_metal_shaders.sh — do not edit.
// Rebuild with: ./build_metal_shaders.sh

#include <TargetConditionals.h>

namespace systems::leal::campello_widgets::shaders {{

{chr(10).join(arrays)}
}} // namespace systems::leal::campello_widgets::shaders

// Metal shader bytecode is platform-specific — select the variant matching
// the SDK this translation unit is actually being compiled for.
#if TARGET_OS_SIMULATOR
#define kWidgetsMetalShader     systems::leal::campello_widgets::shaders::kWidgetsMetalShader_iOSSimulator
#define kWidgetsMetalShaderSize systems::leal::campello_widgets::shaders::kWidgetsMetalShaderSize_iOSSimulator
#elif TARGET_OS_IPHONE
#define kWidgetsMetalShader     systems::leal::campello_widgets::shaders::kWidgetsMetalShader_iOS
#define kWidgetsMetalShaderSize systems::leal::campello_widgets::shaders::kWidgetsMetalShaderSize_iOS
#else
#define kWidgetsMetalShader     systems::leal::campello_widgets::shaders::kWidgetsMetalShader_macOS
#define kWidgetsMetalShaderSize systems::leal::campello_widgets::shaders::kWidgetsMetalShaderSize_macOS
#endif
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}")
PYEOF
