#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders/metal"
OUT_HEADER="$SCRIPT_DIR/src/shaders/metal_widgets.h"

mkdir -p "$SCRIPT_DIR/src/shaders"

# ---------------------------------------------------------------------------
# Compile Metal → AIR → metallib
# ---------------------------------------------------------------------------
echo "Compiling: widgets.metal → widgets.air"
xcrun -sdk macosx metal -c "$SHADER_DIR/widgets.metal" -o "$SHADER_DIR/widgets.air"

echo "Linking:   widgets.air → widgets.metallib"
xcrun -sdk macosx metallib "$SHADER_DIR/widgets.air" -o "$SHADER_DIR/widgets.metallib"

# ---------------------------------------------------------------------------
# Generate header from metallib binary
# ---------------------------------------------------------------------------
python3 - "$SHADER_DIR/widgets.metallib" "$OUT_HEADER" <<'PYEOF'
import sys

def binary_to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

metallib_path, out_path = sys.argv[1], sys.argv[2]

hex_lines, size = binary_to_hex_lines(metallib_path)

header = f"""#pragma once

// Auto-generated by build_metal_shaders.sh — do not edit.
// Rebuild with: ./build_metal_shaders.sh

namespace systems::leal::campello_widgets::shaders {{

static const unsigned char kWidgetsMetalShader[] = {{
{hex_lines}
}};

static const unsigned int kWidgetsMetalShaderSize = {size};

}} // namespace systems::leal::campello_widgets::shaders
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}  ({size} bytes)")
PYEOF
